### ISSUE TITLE
hibernate-5.1+ SQLException: PooledConnection has already been closed.

### ISSUE THREAD

**Issue by zyro23** [grails/gorm-hibernate5#29]
using hibernate-5.1 and above, we see frequent `DEBUG` logs of `java.sql.SQLException: PooledConnection has already been closed.`.

https://jira.spring.io/browse/SPR-14548 looks related. spring adjusts the connection release-/handling-mode to the variants of "on_close" that spring wants/needs.
i think gorm does not use `LocalSessionFactoryBuilder` (ref. https://github.com/spring-projects/spring-framework/commit/fad931d76487e65848bc39c3cbcb6e3def5e6201) and the hibernate defaults are used which are different.

adding the corresponding hibernate config properties makes the excessive `DEBUG` logs go away:
```yml
# hibernate-5.1.x:
hibernate:
    connection:
        release_mode: ON_CLOSE

# hibernate-5.2.x:
hibernate:
    connection:
        handling_mode: DELAYED_ACQUISITION_AND_HOLD
```

would be great if gorm applies those by default, too.

thanks, zyro
